In [ ]:
import numpy as np

Уровень 0:
Задание 1

Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы
Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
m_1 = np.eye(3)
m_1
m_sum = M + m_1
print(m_sum)
v = np.array([1,2,3])
m_mul = m_sum * v # покоординатное умножение

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [ ]:
np.dot(m_sum,v) # m_sum @ v матричное умножение,

array([15., 34., 53.])

In [ ]:
m_sum.T #Вычислить транспонированную матрицу от полученной в результате прибавления матрицы

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
# Посчитайте обратную матрицу к полученной в результате прибавления матрице
m_inv = np.linalg.inv(m_sum)

In [ ]:
m_inv@m_sum # проверю, что при умножении получается единичная матрица
# => Всё ок =)

array([[ 1.00000000e+00,  0.00000000e+00,  3.55271368e-15],
       [-7.77156117e-17,  1.00000000e+00,  1.11022302e-16],
       [ 6.66133815e-16,  0.00000000e+00,  1.00000000e+00]])

Уровень 1:
Задание 2

Найдите собственные значения и собственные вектора матрицы:

In [ ]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
num, v = np.linalg.eig(m)
print(f'собственные значения: {num}\n собственные вектора: {v}')

собственные значения: [1. 4.]
 собственные вектора: [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
a = np.array([[1,2,1],[2,1,1],[1,3,1]])
det = np.linalg.det(a)
# det
# a
print(f'матрица: {a}\n определитель = {det}')

матрица: [[1 2 1]
 [2 1 1]
 [1 3 1]]
 определитель = 1.0
