In [27]:
import numpy as np
from numpy import linalg

In [28]:
"""
Задание 1
Создайте numpy array с элементами от числа N 
до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
"""
N = 10
AR = np.arange(N-1,-1,-1)
AR

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
"""
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
"""
D_M = np.diag(AR, k=0) #AR = np.arange(N-1,-1,-1)
print(D_M)
print(f'sum = {D_M.sum()}')
trace = np.trace(D_M)
print(trace)
diag = np.diagonal(D_M)
print(sum(diag))

"""
правильно понимаю, что 1 считает сумму всех эл-тов?
"""

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
sum = 45
45
45


'\nправильно понимаю, что 1 считает сумму всех эл-тов?\n'

In [30]:
"""
Решите систему уравнений:

1
2
3
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""
x = np.array([[4,2,1],[1,3,0],[0,5,4]])
y = np.array([4,12,3])
linalg.solve(x,y)
# np.allclose(np.dot(x,linalg.solve(x,y)),y) проверка

array([ 0.06666667,  3.97777778, -4.22222222])

In [31]:
"""
Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем:
"""
def cosine(a,b):
  aLen = linalg.norm(a)
  bLen = linalg.norm(b)
  return np.dot(a,b) / (aLen * bLen)
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
max_cos = 0
max_i = -1
for i in range(users_stats.shape[0]):
  cos_i = cosine(next_user_stats,users_stats[i])
  if cos_i > max_cos:
    max_cos = cos_i
    max_i = i

print(f"самый близкий пользователь № {max_i}, вектор покупок: {users_stats[max_i]}") 
#пользователей users_stats с 0 считаем

самый близкий пользователь № 7, вектор покупок: [0 1 1 0 0 0]
